---
layout: cv
title: Rakeb Denboba's
---
# RAKEB DENBOBA
STUDENT MAJORING IN ACCOUNTING

<div id="webaddress">
<a href="RAKEBYARED785@GMAIL.COM">rakebyared785@gmail.com</a>


## Education

`2022 - 2023`
__University of southdakota.__

`september 2023 - now`
__brigham young university of idaho__
  

## Awards
deans list 


## Occupation

`2023 - present`
__student cashier__ brigham young university 
- Process an average of 40 financial transactions daily, including tuition payments, scholarships, and 529 accounts, ensuring timely and accurate processing of cash and check payments. 
- Deliver exceptional customer service by addressing student account inquiries, concerns, and complaints, consistently resolving issues to improve satisfaction. 

- Received specialized training to effectively assist students with various account-related inquiries and resolve issues promptly. 

- Utilize Team Dynamics, iSeries, Feith, and Transact to manage daily cash flow, monitor payment records, and ensure accurate transaction reporting. 

- Utilize Microsoft Excel to track daily cash flow, monitor payment records, and ensure accurate transaction reporting. 

- Created and maintained detailed spreadsheets, improving the accuracy of financial reporting and ensuring balanced registers at the close of each shift.
`april 2024 - july 2024`
__front desk assistant__, brigham young university

- Handled an average of 75 inquiries daily via phone, email, and in-person, efficiently assisting students, faculty, and staff with financial matters, improving overall client satisfaction. 

- Utilized office software, including team dynamics, Microsoft outlook, and google calendar to manage calendars, prioritize emails, and streamline office workflow, increasing administrative efficiency by 29%. 

- Addressed client concerns and facilitated communication between clients and accounting staff to ensure seamless service delivery. 

## Volunteer EXPERIENCE 
Africa Student associatio coordinator       
"September 2020 - July 2023" 

- Coordinate an Africa night, one of the biggest events on campus. 

- Assisted with the marketing and promotion of one of the association’s premier events, helping to increase student awareness and attendance. 

- Facilitated student engagement by helping new international students get accustomed to the new culture, fostering a sense of community and inclusivity during the event.  

- Collaborated in organizing and distributing food, ensuring smooth operations and a positive attendee experience.  

 
<!-- ### Footer

Last updated: May 2013 -->